export enum Operation {
  Insert = 'Insert',
  Update = 'Update',
  Select = 'Select',
  Delete = 'Delete',
  CreateTable = 'CreateTable',
  DropTable = 'DropTable',
  CreateForeignKey = 'CreateForeignKey',
  DropForeignKey = 'DeleteForeignKey',
  CreateIndex = 'CreateIndex',
  DropIndex = 'DeleteIndex',
  AddColumn = 'AddColumn',
  DropColumn = 'DropColumn',
  RenameColumn = 'RenameColumn',
  DropColumnDefaultValue = 'DropColumnDefaultValue',
  SetColumnDefaultValue = 'SetColumnDefaultValue',
  ChangeColumnType = 'ChangeColumnType',
}
